name: Fetch real data and publish JSON

on:
  workflow_dispatch:
  schedule:
    - cron: "5 * * * *"   # هر ساعت در دقیقه ۵ (UTC)

permissions:
  contents: write

concurrency:
  group: fetch-data
  cancel-in-progress: true

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run fetch script
        env:
          FREE_MARKET_PROVIDER: priceto          # priceto | bonbast | tgju
          FREE_MARKET_API_KEY: ${{ secrets.FREE_MARKET_API_KEY }}   # در priceto فعلاً لازم نیست
          BONBAST_API_KEY:      ${{ secrets.BONBAST_API_KEY }}      # اگر Bonbast داشتی
          TGJU_API_KEY:         ${{ secrets.TGJU_API_KEY }}         # اگر TGJU داشتی
          METALS_PROVIDER:      ${{ secrets.METALS_PROVIDER }}
          METALS_API_KEY:       ${{ secrets.METALS_API_KEY }}
          IMAGE_FETCH_LIMIT: "12"
          TRANSLATE_LIMIT:  "30"
        run: python scripts/fetch_data.py

      - name: Commit & Push data (with rebase)
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/data/*.json || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "data: auto-update (free-market fx + gold + news) $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          BRANCH="${{ github.ref_name }}"
          git pull --rebase --autostash origin "$BRANCH" || true
          if ! git push origin HEAD:"$BRANCH"; then
            git push --force-with-lease origin HEAD:"$BRANCH"
          fi
